console.log("question 1");
var fullName = "ChiếnVD";
var age1 = 25;
console.log(" t\u00F4i t\u00EAn l\u00E0 ".concat(fullName, ", n\u0103m nay t\u00F4i ").concat(age1, " tu\u1ED5i. "));
console.log("________________________________");
console.log("question 2");
var a = 5;
var b = 20;
console.log(" T\u1ED5ng c\u1EE7a ".concat(a, " v\u00E0 ").concat(b, " l\u00E0 ").concat(a + b));
console.log("________________________________");
console.log("question 3");
var k = "1. chả giò nón lá";
var l = "2. bò lúc lắc hạt điều";
var e = "3. cá tai tượng chiên xù";
var f = "4. cải thìa sốt thịt cua";
var g = "5. cơm chiên cá mặn";
var h = "6. lẩu hải sản";
var i = "7. rau câu";
console.log(" ".concat(k, "\n ").concat(l, "\n ").concat(e, "\n ").concat(f, "\n ").concat(g, "\n ").concat(h, "\n ").concat(i));
